"""Add Session Table and Modify Messages Table

Revision ID: 30100d2aa298
Revises: 6a3a251adb34
Create Date: 2025-12-12 04:05:25.854913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30100d2aa298'
down_revision: Union[str, Sequence[str], None] = '6a3a251adb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('session_id', sa.Uuid(), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'session', ['session_id'], ['id'])
    op.drop_column('message', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversation_id', sa.CHAR(length=32), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_column('message', 'session_id')
    op.drop_table('session')
    # ### end Alembic commands ###
